[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
APP_ENV = "prod"
COMPOSER_ALLOW_SUPERUSER = "1"
# DATABASE_URL sera configuré via l'interface Railway avec Neon/Supabase